### ISSUE TITLE
write INSTALL targets for CMake

### ISSUE THREAD

**Issue by igor-raits** [Washington-University/CiftiLib#4] opened 2015-11-04 08:33 UTC
I'm packaging CiftiLib for Fedora and I'd want to install all libs and headers to system, but I can't write patch myself because I don't know which headers are public and which are private.

**Comment by coalsont** [comment] 2015-11-04 22:05
That is interesting news.  I'll look into adding install targets, but as I mentioned in #3, I hadn't really thought about shared library use, so I don't currently consider any headers as private.  However, there are a few that could be made private, as they do minor or tangential tasks (FloatMatrix, CompactLookup...).

**Comment by ghisvail** [comment] 2016-03-22 19:38
Same here for packaging in Debian / Ubuntu

**Comment by coalsont** [comment] 2016-03-22 21:31
The shlib-test branch had install targets of all headers, into a Cifti subdirectory.  It now (ae5f6d6904ca186c4b465ad7a4012524df0135e5) excludes some from headers from Common, which were easy to drop, the headers in other directories are all part of the API.

**Comment by coalsont** [comment] 2016-03-22 23:04
shlib-test is now merged into master.

**Comment by ghisvail** [comment] 2016-03-23 00:05
Although it is a reasonable step forward, the current support for static and shared version of the library is not standard.

There should not be a need for different build path for static vs shared build. Both should produce a `libcifti` binary suffixed with either `.so` or `.a`. You may control the type of build using the [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html) CMake variable for instance. I would expect your CMake layout to be pretty similar to what [`NiftiCLib`](http://niftilib.cvs.sourceforge.net/viewvc/niftilib/Clibs/) has got.

One last comment regarding the shared library is its discoverability. For that, you may want to provide a `pkgconfig` file and / or a CMake package file. That way client code can build and link with CiftiLib using either `pkg-config` (for Makefiles) or `find_package` (for CMake) and have all includes, libraries and dependencies set-up automatically. I can point you to specific examples if you are interested.

**Comment by coalsont** [comment] 2016-03-23 00:20
Examples would be nice.

The static build originally made 3 static libraries, one for each directory, and I didn't want to do that with a shared version, and the way I chose to combine them didn't require changing the static setup.  I'm not sure what the simplest way to make a single library from multiple directories of sources is, and I think the directory structure of the sources is somewhat helpful compared to a single directory with all of the source files.

**Comment by ghisvail** [comment] 2016-03-23 08:33
> The static build originally made 3 static libraries, one for each directory, and I didn't want to do that with a shared version

I figured. However, having different byproducts for shared and static builds is definitely non-standard and weird from a packaging perspective.

> the directory structure of the sources is somewhat helpful

In what sense? Do all 3 directories correspond to respective byproducts (libCommon, libCifti and libNifti) that the end-user is expected to interact with? Or should the only byproduct visible to the end-user be just a libCifti binary?

My guess here, and please correct me if I am wrong, is that your source code is not (yet?) organized with a public API in mind. Consider the end-user with some client code that requires manipulation of the Cifti format, where should be the entry-point to the library? My guess is that there should not be that many (afterall, it is an I/O library) and the rest of the code should be implementation details.

A representative example could be the [`Field3D`](https://github.com/imageworks/Field3D) library. For the pkg-config / cmake package file handling, have a look at [`ASL`](https://github.com/AvtechScientific/ASL) in the main `CMakeLists.txt`.

Let me know if you have further questions.

**Comment by coalsont** [comment] 2016-03-23 22:38
So, the stuff in the Cifti/ folder is everything specific to CIFTI format, the Nifti/ folder is general nifti stuff (you can use it for volume files), and Common/ is miscellaneous supporting things (some headers in there are not install targets).  For development of CiftiLib itself, it makes sense to me to separate these things, as there is a clear conceptual divide between them.  If the end user is only interested in using it for CIFTI files, then the stuff in the Cifti/ directory is the most relevant, with just a few things in Common that are used in the API.

The main entry points for dealing specifically with CIFTI files are CiftiFile and CiftiXML, but to convey the detailed information contained in the format in a way convenient for users (we do not want users to have to work with the xml in DOM form, that would be terrible), the other classes in Cifti/ are required (used directly in end-user code), as are the things in Common that are used in their functions (AString, VoxelIJK, Vector3D).  The encoding of the information into CIFTI files is relatively simple compared to the structure of the information itself (CIFTI is not just a 3D+ bitmap the way volume files are), which is why there are that many public classes in Cifti/.  The generic nifti IO code is relatively short, and supports nifti-1 and nifti-2, and gzipped nifti, so it doesn't make sense to make that private from users, telling them to get a separate library for other kinds of nifti files.

For installing the headers, I don't think separate subdirectories makes sense, as that is more effort for the user.  I was just trying to justify the extra work of making a single library file from multiple directories of sources (which I am happy to do the same way for the static case).

**Comment by coalsont** [comment] 2016-03-23 22:49
So, Field3D just puts all the sources into one directory, which is what I'd prefer not to do.  However, I can probably just use my existing shared setup unconditionally, and remove the specification of "SHARED" in it.

**Comment by coalsont** [comment] 2016-03-24 00:36
Unfortunately, I am currently using a cmake version old enough not to have CMakePackageConfigHelpers.  The pkg-config format seems fairly simple, so a manually-written one may be good enough for now (with the caveat that it may need a packaging patch for lib vs lib64).

**Comment by ghisvail** [comment] 2016-03-25 14:10
Thanks for the detailed explanation Tim. My comments below:

> For development of CiftiLib itself, it makes sense to me to separate these things.

And I am not objecting to it. Whatever works best for your indeed.

> The main entry points for dealing specifically with CIFTI files are CiftiFile and CiftiXML [...] which is why there are that many public classes in Cifti/.

Ack.

> The generic nifti IO code is relatively short, and supports nifti-1 and nifti-2, and gzipped nifti, so it doesn't make sense to make that private from users, telling them to get a separate library for other kinds of nifti files.

Since there is no support (yet) for the nifti-2 in nifticlib, I understand why you decided to provide your own implementation.

> For installing the headers, I don't think separate subdirectories makes sense, as that is more effort for the user.

If compiling / linking manually yes. With a pkg-config / CMake package file, this would be handled
transparently.

> I was just trying to justify the extra work of making a single library file from multiple directories of sources (which I am happy to do the same way for the static case).

It does not really matter whether you want to build 1 common library (out of all directories) or 3 separates ones (1 per directory), as long as the static and shared builds produce the same artifacts. Just pick one and stick with it. Then, the definition of the CMake targets should be the same regardless of static vs shared, which is an end-user choice (via `BUILD_SHARED_LIBS`) at the end of the day.

> Unfortunately, I am currently using a cmake version old enough not to have CMakePackageConfigHelpers.

It is pretty recent indeed. You can use plain calls to `configure_file` like [here](https://github.com/clMathLibraries/clBLAS/blob/master/src/CMakeLists.txt).

> The pkg-config format seems fairly simple, so a manually-written one may be good enough for now.

You should consider using a template onto which you will run `configure_file` with the install settings. See link to the ASL project above for a straightforward example.

> with the caveat that it may need a packaging patch for lib vs lib64.

You should consider using [`GnuInstallDirs`](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html), which provides system-agnostic install paths.

Hope this helps,
Ghis

**Comment by coalsont** [comment] 2016-03-25 21:45
how does 4d33bd64411170baa3517e32a6d877d2eb5d1415 look?  Provisionally using CiftiLib as the pkg-config name, I could change it to libCifti to match conventions.

**Comment by ghisvail** [comment] 2016-03-26 14:07
> how does 4d33bd6 look?

Looking good to me. You would need to check, with an example, program whether:
`g++ -o example -I 'pkg-config --cflags CiftiLib' example.cpp -L 'pkg-config --libs CiftiLib'`
Compiles and works as intended.

> Provisionally using CiftiLib as the pkg-config name, I could change it to libCifti to match conventions.

This one is totally your call. There is not much of a naming convention here as far as I have seen. As long as you stick to it for good later.

These pieces of improvement are very welcome. Thanks for addressing our comments.

**Comment by coalsont** [comment] 2016-03-28 19:56
I found that I had forgotten to add the definition that selects the XML parser to the pkg-config file, it works now (after removing the -I and -L in your example).

**Closed as completed by coalsont** 2016-03-28 19:56 UTC

**Comment by coalsont** [comment] 2016-03-29 23:43
> Since there is no support (yet) for the nifti-2 in nifticlib, I understand why you decided to provide your own implementation.

Unfortunately, that is not the whole story - the CIFTI-1 specification unfortunately used the NIfTI-2 header incorrectly, requiring a small hack in the nifti code (NiftiIO::overrideDimensions(...)) in order to read them.  I'm not sure if you can do this in nifticlib, even when it gains NIfTI-2 support.  The dimensions in the nifti header for cifti files are also not like a volume file, which may make it challenging to do efficient on-disk reading/writing of cifti through the current nifticlib functions (I see functions to read bricks, but not more generic ones to read chunks of arbitrary number of initial dimensions, which is how our NiftiIO interface works, so we can read single rows of the cifti matrix).

I'm prepared to make a new release version from current master, but I plan to hold off until you say so, in case you find more things to fix while packaging.

**Comment by ghisvail** [comment] 2016-03-30 06:34
So what you are saying is that the CIFTI-x formats require a patched version of NIFTI to work?

Also, does it mean that CiftiLib can / cannot read a file saved as vanilla NifTI-1 or NifTI-2? Just trying to figure out whether CiftiLib could serve the double purpose of reading both CIFTI-x and NifTI-x formats.

> I'm prepared to make a new release version from current master, but I plan to hold off until you say so, in case you find more things to fix while packaging.

Ok, I'll refresh the packaging with the current tip on `master` and report what I found.

Many thanks for working on this.

**Comment by coalsont** [comment] 2016-03-30 21:17
> So what you are saying is that the CIFTI-x formats require a patched version of NIFTI to work?

If we wanted to use nifticlib, especially for on-disk and for CIFTI-1, it would need some changes to its interface, I believe, yes.  CIFTI-2 will probably work in nifticlib for in-memory usage, though depending on how their data structures are organized, it could be problematic (if they assume volume files, then they might have large arrays of 1x1x1 volumes when they load one, which would be very inefficient).

> Also, does it mean that CiftiLib can / cannot read a file saved as vanilla NifTI-1 or NifTI-2?

It can, though it does not provide a volume-file-oriented class for this (CiftiFile is specialized for Cifti type Nifti files, but NiftiIO is generic low-ish level reading/writing of any kind of Nifti file, including gzipped, and this library doesn't include a VolumeFile specialized class for the vanilla usage of Nifti).  It does not currently support some rarely-used Nifti features, specifically bitwise data encoding or separate header/image pairs (I don't know if I've ever seen Nifti files using these).
